version: '3.8'

services:
  robot-cell-01:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ROBOT-CELL-01"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  robot-cell-02:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ROBOT-CELL-02"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  robot-cell-03:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ROBOT-CELL-03"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  robot-cell-04:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ROBOT-CELL-04"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  robot-cell-05:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ROBOT-CELL-05"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  assembly-st-01:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ASSEMBLY-ST-01"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  assembly-st-02:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ASSEMBLY-ST-02"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  assembly-st-03:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ASSEMBLY-ST-03"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  assembly-st-04:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ASSEMBLY-ST-04"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  assembly-st-05:
    build: 
      context: .
      dockerfile: Dockerfile.simulator
    command: ["--client", "ASSEMBLY-ST-05"]
    environment:
      - GRPC_HOST=host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"
