# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'system_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11system_info.proto\x12\x0bsystem_info\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x01\n\x11SystemInfoRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x1a\n\x12machine_identifier\x18\x02 \x01(\t\x12\x13\n\x0bmac_address\x18\x03 \x01(\t\x12/\n\x0blast_online\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x0fhardware_config\x18\x05 \x01(\x0b\x32\x1b.system_info.HardwareConfig\x12\x34\n\x0fsoftware_config\x18\x06 \x01(\x0b\x32\x1b.system_info.SoftwareConfig\";\n\x0eHardwareConfig\x12\x0b\n\x03\x63pu\x18\x01 \x01(\t\x12\x0b\n\x03ram\x18\x02 \x01(\t\x12\x0f\n\x07storage\x18\x03 \x01(\t\"@\n\x0eSoftwareConfig\x12\x12\n\nos_version\x18\x01 \x01(\t\x12\x1a\n\x12installed_packages\x18\x02 \x03(\t\"6\n\x12SystemInfoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2j\n\x13SystemInfoCollector\x12S\n\x10ReportSystemInfo\x12\x1e.system_info.SystemInfoRequest\x1a\x1f.system_info.SystemInfoResponseB\x14\xaa\x02\x11\x41pp.Shared.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021App.Shared.Protos'
  _globals['_SYSTEMINFOREQUEST']._serialized_start=68
  _globals['_SYSTEMINFOREQUEST']._serialized_end=311
  _globals['_HARDWARECONFIG']._serialized_start=313
  _globals['_HARDWARECONFIG']._serialized_end=372
  _globals['_SOFTWARECONFIG']._serialized_start=374
  _globals['_SOFTWARECONFIG']._serialized_end=438
  _globals['_SYSTEMINFORESPONSE']._serialized_start=440
  _globals['_SYSTEMINFORESPONSE']._serialized_end=494
  _globals['_SYSTEMINFOCOLLECTOR']._serialized_start=496
  _globals['_SYSTEMINFOCOLLECTOR']._serialized_end=602
# @@protoc_insertion_point(module_scope)
