// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using App.Shared.Data;
using App.Shared.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315210216_AddInventoryAndMachine")]
    partial class AddInventoryAndMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("CustomDataPoints")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_data_points");

                    b.Property<Guid?>("FloorPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_plan_id");

                    b.Property<HardwareConfig>("HardwareConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hardware_config");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_identifier");

                    b.Property<string>("PinnedObjectHandle")
                        .HasColumnType("text")
                        .HasColumnName("pinned_object_handle");

                    b.Property<List<PcPredecessor>>("Predecessors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("predecessors");

                    b.Property<SoftwareConfig>("SoftwareConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("software_config");

                    b.HasKey("Id")
                        .HasName("pk_client_pcs");

                    b.HasIndex("FloorPlanId")
                        .HasDatabaseName("ix_client_pcs_floor_plan_id");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_hostname");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_mac_address");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("ix_client_pcs_machine_id");

                    b.HasIndex("PinnedObjectHandle")
                        .HasDatabaseName("ix_client_pcs_pinned_object_handle");

                    b.ToTable("client_pcs", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("AdminManagedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("admin_managed_fields");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.FloorPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<FloorPlanAnchor>>("Anchors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("anchors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SvgContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("svg_content");

                    b.HasKey("Id")
                        .HasName("pk_floor_plans");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_floor_plans_name");

                    b.ToTable("floor_plans", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.HardwareComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CostInHUF")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_in_huf");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("RetailerCode")
                        .HasColumnType("text")
                        .HasColumnName("retailer_code");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_hardware_components");

                    b.ToTable("hardware_components", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom_identifier");

                    b.Property<JsonDocument>("HwComponents")
                        .HasColumnType("jsonb")
                        .HasColumnName("hw_components");

                    b.Property<JsonDocument>("SwComponents")
                        .HasColumnType("jsonb")
                        .HasColumnName("sw_components");

                    b.HasKey("Id")
                        .HasName("pk_machines");

                    b.HasIndex("CustomIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_machines_custom_identifier");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CostInHUF")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_in_huf");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("RetailerCode")
                        .HasColumnType("text")
                        .HasColumnName("retailer_code");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_software_components");

                    b.ToTable("software_components", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Privileges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("privileges");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_name");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.HasOne("App.Shared.Entities.Machine", "Machine")
                        .WithMany("Clients")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_client_pcs_machines_machine_id");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
