// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using App.Shared.Data;
using App.Shared.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310201850_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("CustomDataPoints")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_data_points");

                    b.Property<HardwareConfig>("HardwareConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hardware_config");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("MachineIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_identifier");

                    b.Property<List<PcPredecessor>>("Predecessors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("predecessors");

                    b.Property<SoftwareConfig>("SoftwareConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("software_config");

                    b.HasKey("Id")
                        .HasName("pk_client_pcs");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_hostname");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_mac_address");

                    b.ToTable("client_pcs", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("AdminManagedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("admin_managed_fields");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.ToTable("components", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
