// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using App.Shared.Data;
using App.Shared.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330203125_AddInventoryRefinementsAndMonitoring")]
    partial class AddInventoryRefinementsAndMonitoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("backend")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Shared.Entities.AlertingLimits", b =>
                {
                    b.Property<double>("CpuThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_threshold");

                    b.Property<double>("DiskFreeSpaceMinGB")
                        .HasColumnType("double precision")
                        .HasColumnName("disk_free_space_min_gb");

                    b.Property<double>("RamThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("ram_threshold");

                    b.ToTable("alerting_limits", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_member");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_member_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_member_user_id");

                    b.ToTable("member", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.AuthOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.ToTable("organization", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActiveOrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("active_organization_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user_id");

                    b.ToTable("session", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.AuthUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_expires_at");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<bool?>("Banned")
                        .HasColumnType("boolean")
                        .HasColumnName("banned");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<AlertingLimits>("AlertingLimits")
                        .HasColumnType("jsonb")
                        .HasColumnName("alerting_limits");

                    b.Property<JsonDocument>("CustomDataPoints")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_data_points");

                    b.Property<Guid?>("FloorPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_plan_id");

                    b.Property<DiskSpaceInfo>("FreeDiskSpace")
                        .HasColumnType("jsonb")
                        .HasColumnName("free_disk_space");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("MachineIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_identifier");

                    b.Property<ResourceMonitoringConfig>("MonitoringConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("monitoring_config");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("PinnedObjectHandle")
                        .HasColumnType("text")
                        .HasColumnName("pinned_object_handle");

                    b.Property<List<PcPredecessor>>("Predecessors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("predecessors");

                    b.Property<ResourceAverages>("ResourceAverages")
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_averages");

                    b.HasKey("Id")
                        .HasName("pk_client_pcs");

                    b.HasIndex("FloorPlanId")
                        .HasDatabaseName("ix_client_pcs_floor_plan_id");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_hostname");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_mac_address");

                    b.HasIndex("PinnedObjectHandle")
                        .HasDatabaseName("ix_client_pcs_pinned_object_handle");

                    b.ToTable("client_pcs", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.DiskSpaceInfo", b =>
                {
                    b.Property<double>("OsDriveFreeGB")
                        .HasColumnType("double precision")
                        .HasColumnName("os_drive_free_gb");

                    b.Property<double>("TotalFreeGB")
                        .HasColumnType("double precision")
                        .HasColumnName("total_free_gb");

                    b.ToTable("disk_space_info", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.FloorPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<FloorPlanAnchor>>("Anchors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("anchors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SvgContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("svg_content");

                    b.HasKey("Id")
                        .HasName("pk_floor_plans");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_floor_plans_name");

                    b.ToTable("floor_plans", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.FloorPlanAnchor", b =>
                {
                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.ToTable("floor_plan_anchor", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.InventoryComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text")
                        .HasColumnName("cost_center");

                    b.Property<string>("CostCenterOU")
                        .HasColumnType("text")
                        .HasColumnName("cost_center_ou");

                    b.Property<JsonDocument>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityCreator")
                        .HasColumnType("text")
                        .HasColumnName("entity_creator");

                    b.Property<string>("EntityUpdater")
                        .HasColumnType("text")
                        .HasColumnName("entity_updater");

                    b.Property<Guid?>("LateralLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("lateral_link_id");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Technology")
                        .HasColumnType("text")
                        .HasColumnName("technology");

                    b.Property<ComponentTopLevelFlags>("TopLevelFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("top_level_flags");

                    b.HasKey("Id")
                        .HasName("pk_inventory_components");

                    b.HasIndex("ClientPcId")
                        .HasDatabaseName("ix_inventory_components_client_pc_id");

                    b.HasIndex("LateralLinkId")
                        .HasDatabaseName("ix_inventory_components_lateral_link_id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("ix_inventory_components_machine_id");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_inventory_components_manufacturer_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_inventory_components_parent_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_inventory_components_supplier_id");

                    b.ToTable("inventory_components", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom_identifier");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("PinnedObjectHandle")
                        .HasColumnType("text")
                        .HasColumnName("pinned_object_handle");

                    b.HasKey("Id")
                        .HasName("pk_machines");

                    b.HasIndex("CustomIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_machines_custom_identifier");

                    b.ToTable("machines", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SupportContact")
                        .HasColumnType("text")
                        .HasColumnName("support_contact");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_manufacturers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturers_name");

                    b.ToTable("manufacturers", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.PcPredecessor", b =>
                {
                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.ToTable("pc_predecessor", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.ResourceAverages", b =>
                {
                    b.Property<double>("CpuUsageAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_usage_average");

                    b.Property<double>("DiskIoAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("disk_io_average");

                    b.Property<DateTimeOffset>("LastCalculated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_calculated");

                    b.Property<double>("RamUsageAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("ram_usage_average");

                    b.ToTable("resource_averages", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.ResourceMonitoringConfig", b =>
                {
                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<int>("SamplingIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("sampling_interval_seconds");

                    b.ToTable("resource_monitoring_config", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_name");

                    b.ToTable("suppliers", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Privileges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("privileges");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_name");

                    b.ToTable("user_roles", "backend");
                });

            modelBuilder.Entity("ClientPcMachine", b =>
                {
                    b.Property<Guid>("ClientPcsId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pcs_id");

                    b.Property<Guid>("MachinesId")
                        .HasColumnType("uuid")
                        .HasColumnName("machines_id");

                    b.HasKey("ClientPcsId", "MachinesId")
                        .HasName("pk_client_pc_machine");

                    b.HasIndex("MachinesId")
                        .HasDatabaseName("ix_client_pc_machine_machines_id");

                    b.ToTable("ClientPcMachine", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthMember", b =>
                {
                    b.HasOne("App.Shared.Entities.AuthOrganization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_organization_organization_id");

                    b.HasOne("App.Shared.Entities.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_user_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthSession", b =>
                {
                    b.HasOne("App.Shared.Entities.AuthUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Shared.Entities.InventoryComponent", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", "ClientPc")
                        .WithMany("Components")
                        .HasForeignKey("ClientPcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_inventory_components_client_pcs_client_pc_id");

                    b.HasOne("App.Shared.Entities.InventoryComponent", "LateralLink")
                        .WithMany()
                        .HasForeignKey("LateralLinkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_components_inventory_components_lateral_link_id");

                    b.HasOne("App.Shared.Entities.Machine", "Machine")
                        .WithMany("Components")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_inventory_components_machines_machine_id");

                    b.HasOne("App.Shared.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_components_manufacturers_manufacturer_id");

                    b.HasOne("App.Shared.Entities.InventoryComponent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_inventory_components_inventory_components_parent_id");

                    b.HasOne("App.Shared.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_components_suppliers_supplier_id");

                    b.Navigation("ClientPc");

                    b.Navigation("LateralLink");

                    b.Navigation("Machine");

                    b.Navigation("Manufacturer");

                    b.Navigation("Parent");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ClientPcMachine", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", null)
                        .WithMany()
                        .HasForeignKey("ClientPcsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pc_machine_client_pcs_client_pcs_id");

                    b.HasOne("App.Shared.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pc_machine_machines_machines_id");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthOrganization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthUser", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("App.Shared.Entities.InventoryComponent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
