// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using App.Shared.Data;
using App.Shared.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324214012_AddCategoryTaggingSystem")]
    partial class AddCategoryTaggingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Shared.Entities.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActiveOrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("active_organization_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user_id");

                    b.ToTable("session", "heimdall_dev_db", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.AuthUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_expires_at");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<bool?>("Banned")
                        .HasColumnType("boolean")
                        .HasColumnName("banned");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "heimdall_dev_db", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("CustomDataPoints")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_data_points");

                    b.Property<Guid?>("FloorPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_plan_id");

                    b.Property<HardwareConfig>("HardwareConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hardware_config");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("MachineIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_identifier");

                    b.Property<string>("PinnedObjectHandle")
                        .HasColumnType("text")
                        .HasColumnName("pinned_object_handle");

                    b.Property<List<PcPredecessor>>("Predecessors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("predecessors");

                    b.Property<SoftwareConfig>("SoftwareConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("software_config");

                    b.HasKey("Id")
                        .HasName("pk_client_pcs");

                    b.HasIndex("FloorPlanId")
                        .HasDatabaseName("ix_client_pcs_floor_plan_id");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_hostname");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_mac_address");

                    b.HasIndex("PinnedObjectHandle")
                        .HasDatabaseName("ix_client_pcs_pinned_object_handle");

                    b.ToTable("client_pcs", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("AdminManagedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("admin_managed_fields");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.FloorPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<FloorPlanAnchor>>("Anchors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("anchors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SvgContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("svg_content");

                    b.HasKey("Id")
                        .HasName("pk_floor_plans");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_floor_plans_name");

                    b.ToTable("floor_plans", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.FloorPlanAnchor", b =>
                {
                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.ToTable("floor_plan_anchor", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.HardwareComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CostInHUF")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_in_huf");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("text")
                        .HasColumnName("model_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Revision")
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<ComponentTechnicalSpecs>("TechnicalSpecs")
                        .HasColumnType("jsonb")
                        .HasColumnName("technical_specs");

                    b.HasKey("Id")
                        .HasName("pk_hardware_components");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_hardware_components_manufacturer_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_hardware_components_parent_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_hardware_components_supplier_id");

                    b.ToTable("hardware_components", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom_identifier");

                    b.Property<JsonDocument>("HwComponents")
                        .HasColumnType("jsonb")
                        .HasColumnName("hw_components");

                    b.Property<string>("PinnedObjectHandle")
                        .HasColumnType("text")
                        .HasColumnName("pinned_object_handle");

                    b.Property<JsonDocument>("SwComponents")
                        .HasColumnType("jsonb")
                        .HasColumnName("sw_components");

                    b.HasKey("Id")
                        .HasName("pk_machines");

                    b.HasIndex("CustomIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_machines_custom_identifier");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SupportContact")
                        .HasColumnType("text")
                        .HasColumnName("support_contact");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_manufacturers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturers_name");

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.PcPredecessor", b =>
                {
                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.ToTable("pc_predecessor", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CostInHUF")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_in_huf");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_software_components");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_software_components_manufacturer_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_software_components_parent_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_software_components_supplier_id");

                    b.ToTable("software_components", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_name");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Privileges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("privileges");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_name");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ClientPcMachine", b =>
                {
                    b.Property<Guid>("ClientPcsId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pcs_id");

                    b.Property<Guid>("MachinesId")
                        .HasColumnType("uuid")
                        .HasColumnName("machines_id");

                    b.HasKey("ClientPcsId", "MachinesId")
                        .HasName("pk_client_pc_machine");

                    b.HasIndex("MachinesId")
                        .HasDatabaseName("ix_client_pc_machine_machines_id");

                    b.ToTable("ClientPcMachine", (string)null);
                });

            modelBuilder.Entity("App.Shared.Entities.AuthSession", b =>
                {
                    b.HasOne("App.Shared.Entities.AuthUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Shared.Entities.HardwareComponent", b =>
                {
                    b.HasOne("App.Shared.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_hardware_components_manufacturers_manufacturer_id");

                    b.HasOne("App.Shared.Entities.HardwareComponent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_hardware_components_hardware_components_parent_id");

                    b.HasOne("App.Shared.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_hardware_components_suppliers_supplier_id");

                    b.Navigation("Manufacturer");

                    b.Navigation("Parent");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareComponent", b =>
                {
                    b.HasOne("App.Shared.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_software_components_manufacturers_manufacturer_id");

                    b.HasOne("App.Shared.Entities.SoftwareComponent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_software_components_software_components_parent_id");

                    b.HasOne("App.Shared.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_software_components_suppliers_supplier_id");

                    b.Navigation("Manufacturer");

                    b.Navigation("Parent");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ClientPcMachine", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", null)
                        .WithMany()
                        .HasForeignKey("ClientPcsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pc_machine_client_pcs_client_pcs_id");

                    b.HasOne("App.Shared.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pc_machine_machines_machines_id");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthUser", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("App.Shared.Entities.HardwareComponent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareComponent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
