// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using App.Shared.Data;
using App.Shared.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("backend")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Shared.Entities.AgentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_agent_events");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_agent_events_level");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_agent_events_organization_id");

                    b.HasIndex("ClientPcId", "Timestamp")
                        .HasDatabaseName("ix_agent_events_client_pc_id_timestamp");

                    b.ToTable("agent_events", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("new_values_json");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("old_values_json");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_audit_logs_organization_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_member");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_member_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_member_user_id");

                    b.ToTable("member", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.AuthOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.ToTable("organization", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActiveOrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("active_organization_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user_id");

                    b.ToTable("session", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.AuthUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("App.Shared.Entities.BaseInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<decimal?>("CostInHUF")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_in_huf");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientPcId")
                        .HasDatabaseName("ix_inventory_items_client_pc_id");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_inventory_items_manufacturer_id");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_inventory_items_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_inventory_items_parent_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_inventory_items_supplier_id");

                    b.ToTable("inventory_items", "backend");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("App.Shared.Entities.ClientCertificateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("common_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("thumbprint");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_client_certificates");

                    b.HasIndex("ClientPcId")
                        .HasDatabaseName("ix_client_certificates_client_pc_id");

                    b.HasIndex("CommonName")
                        .HasDatabaseName("ix_client_certificates_common_name");

                    b.HasIndex("Thumbprint")
                        .HasDatabaseName("ix_client_certificates_thumbprint");

                    b.ToTable("client_certificates", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<AlertingLimits>("AlertingLimits")
                        .HasColumnType("jsonb")
                        .HasColumnName("alerting_limits");

                    b.Property<DiskSpaceInfo>("FreeDiskSpace")
                        .HasColumnType("jsonb")
                        .HasColumnName("free_disk_space");

                    b.Property<string>("Hostname")
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("MachineIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("machine_identifier");

                    b.Property<ResourceMonitoringConfig>("MonitoringConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("monitoring_config");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PinnedObjectHandle")
                        .HasColumnType("text")
                        .HasColumnName("pinned_object_handle");

                    b.Property<ResourceAverages>("ResourceAverages")
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_averages");

                    b.Property<JsonDocument>("SystemMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("system_metadata");

                    b.HasKey("Id")
                        .HasName("pk_client_pcs");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_client_pcs_hostname");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_client_pcs_mac_address");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_client_pcs_organization_id");

                    b.HasIndex("SystemMetadata")
                        .HasDatabaseName("ix_client_pcs_system_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SystemMetadata"), "gin");

                    b.ToTable("client_pcs", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.EquipmentInterconnect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InterconnectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interconnect_type");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("PortOrAddress")
                        .HasColumnType("text")
                        .HasColumnName("port_or_address");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<Guid>("SourceEquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_equipment_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetEquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_equipment_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_interconnects");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_equipment_interconnects_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("SourceEquipmentId")
                        .HasDatabaseName("ix_equipment_interconnects_source_equipment_id");

                    b.HasIndex("TargetEquipmentId")
                        .HasDatabaseName("ix_equipment_interconnects_target_equipment_id");

                    b.ToTable("equipment_interconnects", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.FloorPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<FloorPlanAnchor>>("Anchors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("anchors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SvgContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("svg_content");

                    b.HasKey("Id")
                        .HasName("pk_floor_plans");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_floor_plans_name");

                    b.ToTable("floor_plans", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.FloorPlanAnchor", b =>
                {
                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.ToTable("floor_plan_anchor", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.MaintenanceTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to");

                    b.Property<Guid?>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_tickets");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_maintenance_tickets_assigned_to");

                    b.HasIndex("ClientPcId")
                        .HasDatabaseName("ix_maintenance_tickets_client_pc_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_maintenance_tickets_created_at");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_maintenance_tickets_equipment_id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("ix_maintenance_tickets_machine_id");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_maintenance_tickets_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_maintenance_tickets_organization_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_maintenance_tickets_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_maintenance_tickets_status");

                    b.ToTable("maintenance_tickets", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.MalformedTelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_reason");

                    b.Property<string>("IngestionChannel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ingestion_channel");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_at");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_identifier");

                    b.HasKey("Id")
                        .HasName("pk_malformed_telemetry_quarantine");

                    b.HasIndex("IngestionChannel")
                        .HasDatabaseName("ix_malformed_telemetry_quarantine_ingestion_channel");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_malformed_telemetry_quarantine_organization_id");

                    b.HasIndex("QuarantinedAt")
                        .HasDatabaseName("ix_malformed_telemetry_quarantine_quarantined_at");

                    b.ToTable("malformed_telemetry_quarantine", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SupportContact")
                        .HasColumnType("text")
                        .HasColumnName("support_contact");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_manufacturers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturers_name");

                    b.ToTable("manufacturers", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.QueuedAgentCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Signature")
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_queued_agent_commands");

                    b.HasIndex("ClientPcId")
                        .HasDatabaseName("ix_queued_agent_commands_client_pc_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_queued_agent_commands_organization_id");

                    b.ToTable("queued_agent_commands", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.ResponsibleTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_responsible_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_responsible_teams_name");

                    b.ToTable("responsible_teams", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.SchemaVersionManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MigrationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("migration_name");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_schema_version_manifest");

                    b.HasIndex("SchemaVersion")
                        .HasDatabaseName("ix_schema_version_manifest_schema_version");

                    b.ToTable("schema_version_manifest", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.SecurityGroupMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("GroupIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("group_identifier");

                    b.Property<string>("IdentityProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identity_provider");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MappedRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mapped_role");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_security_group_mappings");

                    b.HasIndex("GroupIdentifier")
                        .HasDatabaseName("ix_security_group_mappings_group_identifier");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_security_group_mappings_organization_id");

                    b.ToTable("security_group_mappings", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.StationController", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_station_controllers");

                    b.HasIndex("ClientPcId")
                        .HasDatabaseName("ix_station_controllers_client_pc_id");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_station_controllers_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("MachineId", "ClientPcId")
                        .IsUnique()
                        .HasDatabaseName("ix_station_controllers_machine_id_client_pc_id");

                    b.ToTable("StationControllers", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_name");

                    b.ToTable("suppliers", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_json");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_system_settings_category");

                    b.ToTable("system_settings", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<Guid>("MaintenanceTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_ticket_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_attachments");

                    b.HasIndex("MaintenanceTicketId")
                        .HasDatabaseName("ix_ticket_attachments_maintenance_ticket_id");

                    b.ToTable("ticket_attachments", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MaintenanceTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("MaintenanceTicketId")
                        .HasDatabaseName("ix_ticket_comments_maintenance_ticket_id");

                    b.ToTable("ticket_comments", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("Privileges")
                        .HasColumnType("jsonb")
                        .HasColumnName("privileges");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.ToTable("user_roles", "backend");
                });

            modelBuilder.Entity("BaseInventoryItemResponsibleTeam", b =>
                {
                    b.Property<Guid>("ManagedItemsId")
                        .HasColumnType("uuid")
                        .HasColumnName("managed_items_id");

                    b.Property<Guid>("ResponsibleTeamsId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_teams_id");

                    b.HasKey("ManagedItemsId", "ResponsibleTeamsId")
                        .HasName("pk_item_responsibilities");

                    b.HasIndex("ResponsibleTeamsId")
                        .HasDatabaseName("ix_item_responsibilities_responsible_teams_id");

                    b.ToTable("ItemResponsibilities", "backend");
                });

            modelBuilder.Entity("ClientPcResponsibleTeam", b =>
                {
                    b.Property<Guid>("ClientPcId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_pc_id");

                    b.Property<Guid>("ResponsibleTeamsId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_teams_id");

                    b.HasKey("ClientPcId", "ResponsibleTeamsId")
                        .HasName("pk_pc_responsibilities");

                    b.HasIndex("ResponsibleTeamsId")
                        .HasDatabaseName("ix_pc_responsibilities_responsible_teams_id");

                    b.ToTable("PcResponsibilities", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.HardwareComponent", b =>
                {
                    b.HasBaseType("App.Shared.Entities.BaseInventoryItem");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("text")
                        .HasColumnName("model_number");

                    b.Property<string>("Revision")
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.ToTable("hardware_assets", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.HasBaseType("App.Shared.Entities.BaseInventoryItem");

                    b.Property<string>("CustomIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom_identifier");

                    b.Property<string>("PinnedObjectHandle")
                        .HasColumnType("text")
                        .HasColumnName("pinned_object_handle");

                    b.ToTable("stations", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.PcHardware", b =>
                {
                    b.HasBaseType("App.Shared.Entities.BaseInventoryItem");

                    b.Property<string>("Capacity")
                        .HasColumnType("text")
                        .HasColumnName("capacity");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.ToTable("pc_hardware", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareAsset", b =>
                {
                    b.HasBaseType("App.Shared.Entities.BaseInventoryItem");

                    b.Property<Guid?>("HardwareComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("hardware_component_id");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("text")
                        .HasColumnName("license_key");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasIndex("HardwareComponentId")
                        .HasDatabaseName("ix_software_assets_hardware_component_id");

                    b.ToTable("software_assets", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareComponent", b =>
                {
                    b.HasBaseType("App.Shared.Entities.SoftwareAsset");

                    b.ToTable("software_components", "backend");
                });

            modelBuilder.Entity("App.Shared.Entities.AgentEvent", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", null)
                        .WithMany("Events")
                        .HasForeignKey("ClientPcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_events_client_pcs_client_pc_id");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthMember", b =>
                {
                    b.HasOne("App.Shared.Entities.AuthOrganization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_organization_organization_id");

                    b.HasOne("App.Shared.Entities.AuthUser", "User")
                        .WithMany("Members")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_user_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthSession", b =>
                {
                    b.HasOne("App.Shared.Entities.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Shared.Entities.BaseInventoryItem", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", "ClientPc")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ClientPcId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_items_client_pcs_client_pc_id");

                    b.HasOne("App.Shared.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_items_manufacturers_manufacturer_id");

                    b.HasOne("App.Shared.Entities.BaseInventoryItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_inventory_items_inventory_items_parent_id");

                    b.HasOne("App.Shared.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_items_suppliers_supplier_id");

                    b.Navigation("ClientPc");

                    b.Navigation("Manufacturer");

                    b.Navigation("Parent");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("App.Shared.Entities.EquipmentInterconnect", b =>
                {
                    b.HasOne("App.Shared.Entities.BaseInventoryItem", "SourceEquipment")
                        .WithMany()
                        .HasForeignKey("SourceEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_interconnects_inventory_items_source_equipment_id");

                    b.HasOne("App.Shared.Entities.BaseInventoryItem", "TargetEquipment")
                        .WithMany()
                        .HasForeignKey("TargetEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_interconnects_inventory_items_target_equipment_id");

                    b.Navigation("SourceEquipment");

                    b.Navigation("TargetEquipment");
                });

            modelBuilder.Entity("App.Shared.Entities.MaintenanceTicket", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", "ClientPc")
                        .WithMany()
                        .HasForeignKey("ClientPcId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_maintenance_tickets_client_pcs_client_pc_id");

                    b.HasOne("App.Shared.Entities.BaseInventoryItem", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_maintenance_tickets_inventory_items_equipment_id");

                    b.HasOne("App.Shared.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_maintenance_tickets_stations_machine_id");

                    b.Navigation("ClientPc");

                    b.Navigation("Equipment");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("App.Shared.Entities.QueuedAgentCommand", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", null)
                        .WithMany("PendingCommands")
                        .HasForeignKey("ClientPcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queued_agent_commands_client_pcs_client_pc_id");
                });

            modelBuilder.Entity("App.Shared.Entities.StationController", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", "ClientPc")
                        .WithMany("StationControllers")
                        .HasForeignKey("ClientPcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_controllers_client_pcs_client_pc_id");

                    b.HasOne("App.Shared.Entities.Machine", "Machine")
                        .WithMany("StationControllers")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_controllers_stations_machine_id");

                    b.Navigation("ClientPc");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("App.Shared.Entities.TicketAttachment", b =>
                {
                    b.HasOne("App.Shared.Entities.MaintenanceTicket", "MaintenanceTicket")
                        .WithMany("Attachments")
                        .HasForeignKey("MaintenanceTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_attachments_maintenance_tickets_maintenance_ticket_id");

                    b.Navigation("MaintenanceTicket");
                });

            modelBuilder.Entity("App.Shared.Entities.TicketComment", b =>
                {
                    b.HasOne("App.Shared.Entities.MaintenanceTicket", "MaintenanceTicket")
                        .WithMany("Comments")
                        .HasForeignKey("MaintenanceTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_maintenance_tickets_maintenance_ticket_id");

                    b.Navigation("MaintenanceTicket");
                });

            modelBuilder.Entity("BaseInventoryItemResponsibleTeam", b =>
                {
                    b.HasOne("App.Shared.Entities.BaseInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ManagedItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_responsibilities_inventory_items_managed_items_id");

                    b.HasOne("App.Shared.Entities.ResponsibleTeam", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleTeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_responsibilities_responsible_teams_responsible_teams_id");
                });

            modelBuilder.Entity("ClientPcResponsibleTeam", b =>
                {
                    b.HasOne("App.Shared.Entities.ClientPc", null)
                        .WithMany()
                        .HasForeignKey("ClientPcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pc_responsibilities_client_pcs_client_pc_id");

                    b.HasOne("App.Shared.Entities.ResponsibleTeam", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleTeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pc_responsibilities_responsible_teams_responsible_teams_id");
                });

            modelBuilder.Entity("App.Shared.Entities.HardwareComponent", b =>
                {
                    b.HasOne("App.Shared.Entities.BaseInventoryItem", null)
                        .WithOne()
                        .HasForeignKey("App.Shared.Entities.HardwareComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_assets_inventory_items_id");
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.HasOne("App.Shared.Entities.BaseInventoryItem", null)
                        .WithOne()
                        .HasForeignKey("App.Shared.Entities.Machine", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stations_inventory_items_id");
                });

            modelBuilder.Entity("App.Shared.Entities.PcHardware", b =>
                {
                    b.HasOne("App.Shared.Entities.BaseInventoryItem", null)
                        .WithOne()
                        .HasForeignKey("App.Shared.Entities.PcHardware", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pc_hardware_inventory_items_id");
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareAsset", b =>
                {
                    b.HasOne("App.Shared.Entities.HardwareComponent", null)
                        .WithMany("Firmware")
                        .HasForeignKey("HardwareComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_software_assets_hardware_assets_hardware_component_id");

                    b.HasOne("App.Shared.Entities.BaseInventoryItem", null)
                        .WithOne()
                        .HasForeignKey("App.Shared.Entities.SoftwareAsset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_software_assets_inventory_items_id");
                });

            modelBuilder.Entity("App.Shared.Entities.SoftwareComponent", b =>
                {
                    b.HasOne("App.Shared.Entities.SoftwareAsset", null)
                        .WithOne()
                        .HasForeignKey("App.Shared.Entities.SoftwareComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_software_components_software_assets_id");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthOrganization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("App.Shared.Entities.AuthUser", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("App.Shared.Entities.BaseInventoryItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("App.Shared.Entities.ClientPc", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("InventoryItems");

                    b.Navigation("PendingCommands");

                    b.Navigation("StationControllers");
                });

            modelBuilder.Entity("App.Shared.Entities.MaintenanceTicket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("App.Shared.Entities.HardwareComponent", b =>
                {
                    b.Navigation("Firmware");
                });

            modelBuilder.Entity("App.Shared.Entities.Machine", b =>
                {
                    b.Navigation("StationControllers");
                });
#pragma warning restore 612, 618
        }
    }
}
