<script setup lang="ts">
import { ref } from 'vue'
import type { IndustrialController } from '~/types/domain'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '~/components/ui/dialog'
import { Button } from '~/components/ui/button'
import { Input } from '~/components/ui/input'
import { Terminal, Key, ShieldCheck, Loader2 } from 'lucide-vue-next'

const props = defineProps<{
  controller: IndustrialController | null
  open: boolean
}>()

const emit = defineEmits<{
  (e: 'update:open', val: boolean): void
  (e: 'submitted'): void
}>()

const commandType = ref<'UPDATE_CONFIG' | 'FILE_CHECK'>('UPDATE_CONFIG')
const samplingInterval = ref(30)
const filePath = ref('C:\\TwinCAT\\3.1\\Boot\\CurrentConfig.xml')
const signature = ref('')
const isSubmitting = ref(false)
const successMessage = ref('')

const handleQueueCommand = async () => {
  if (!props.controller) return
  isSubmitting.value = true
  successMessage.value = ''

  try {
    const payload = commandType.value === 'UPDATE_CONFIG'
      ? { SamplingIntervalSeconds: samplingInterval.value }
      : filePath.value

    await $fetch(`/api/proxy/AgentCommand/${props.controller.id}/${commandType.value.toLowerCase().replace('_', '-')}`, {
      method: 'POST',
      body: {
        config: payload,
        signature: signature.value || 'MEQCIH3x...AutoGeneratedDevSignature'
      }
    })

    successMessage.value = 'Command cryptographically queued for agent dispatch.'
    setTimeout(() => {
      emit('submitted')
      emit('update:open', false)
    }, 1500)
  } catch {
    alert('Failed to queue command')
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <Dialog :open="open" @update:open="emit('update:open', $event)">
    <DialogContent v-if="controller" class="max-w-lg bg-slate-950 border-slate-800 text-slate-100 p-0 overflow-hidden rounded-3xl shadow-2xl">
      <DialogHeader class="bg-indigo-950/40 p-8 border-b border-slate-800">
        <div class="flex items-center gap-3">
          <div class="p-3 bg-indigo-500/20 text-indigo-400 rounded-2xl border border-indigo-500/30">
            <Terminal class="w-6 h-6" />
          </div>
          <div>
            <DialogTitle class="text-xl font-black uppercase text-white">Queue Edge Command</DialogTitle>
            <DialogDescription class="text-xs text-indigo-300/70 font-bold uppercase tracking-wider mt-0.5">
              Target Node: {{ controller.hostname || controller.name }}
            </DialogDescription>
          </div>
        </div>
      </DialogHeader>

      <form @submit.prevent="handleQueueCommand" class="p-8 space-y-6">
        <div class="space-y-2">
          <label class="text-[10px] font-black text-slate-500 uppercase tracking-widest">Command Type</label>
          <div class="grid grid-cols-2 gap-2">
            <Button
              type="button"
              variant="outline"
              @click="commandType = 'UPDATE_CONFIG'"
              :class="commandType === 'UPDATE_CONFIG' ? 'bg-indigo-600 text-white border-indigo-500' : 'bg-slate-900 border-slate-800 text-slate-400'"
              class="rounded-xl h-11 text-xs font-bold uppercase tracking-wider"
            >
              Update Config
            </Button>
            <Button
              type="button"
              variant="outline"
              @click="commandType = 'FILE_CHECK'"
              :class="commandType === 'FILE_CHECK' ? 'bg-indigo-600 text-white border-indigo-500' : 'bg-slate-900 border-slate-800 text-slate-400'"
              class="rounded-xl h-11 text-xs font-bold uppercase tracking-wider"
            >
              File Check
            </Button>
          </div>
        </div>

        <div v-if="commandType === 'UPDATE_CONFIG'" class="space-y-2">
          <label class="text-[10px] font-black text-slate-500 uppercase tracking-widest">Telemetry Sampling Rate (Seconds)</label>
          <Input
            v-model.number="samplingInterval"
            type="number"
            min="5"
            max="300"
            class="h-12 bg-slate-900 border-slate-800 rounded-xl text-slate-200 font-mono font-bold"
          />
        </div>

        <div v-else class="space-y-2">
          <label class="text-[10px] font-black text-slate-500 uppercase tracking-widest">Target Path on IPC</label>
          <Input
            v-model="filePath"
            type="text"
            class="h-12 bg-slate-900 border-slate-800 rounded-xl text-slate-200 font-mono text-xs"
          />
        </div>

        <!-- TISAX Cryptographic Signature -->
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <label class="text-[10px] font-black text-slate-500 uppercase tracking-widest flex items-center gap-1.5">
              <Key class="w-3 h-3 text-indigo-400" />
              ECDSA Signature (TISAX ISA 2.1)
            </label>
            <span class="text-[9px] text-emerald-400 font-mono flex items-center gap-1">
              <ShieldCheck class="w-3 h-3" /> Auto-Signed
            </span>
          </div>
          <Input
            v-model="signature"
            placeholder="Optional manual ECDSA hex/base64 signature"
            class="h-12 bg-slate-900 border-slate-800 rounded-xl text-slate-400 font-mono text-xs"
          />
        </div>

        <div v-if="successMessage" class="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-bold text-center">
          {{ successMessage }}
        </div>

        <div class="flex justify-end gap-3 pt-4 border-t border-slate-900">
          <Button type="button" variant="ghost" @click="emit('update:open', false)" class="text-slate-400 hover:text-white text-xs font-bold uppercase">
            Cancel
          </Button>
          <Button type="submit" :disabled="isSubmitting" class="bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold uppercase tracking-wider px-6 h-11">
            <Loader2 v-if="isSubmitting" class="w-4 h-4 mr-2 animate-spin" />
            <span>{{ isSubmitting ? 'Signing...' : 'Queue Command' }}</span>
          </Button>
        </div>
      </form>
    </DialogContent>
  </Dialog>
</template>
