syntax = "proto3";

option csharp_namespace = "App.Shared.Protos";

package system_info;

import "google/protobuf/timestamp.proto";

service SystemInfoCollector {
  rpc ReportSystemInfo (SystemInfoRequest) returns (SystemInfoResponse);
}

message SystemInfoRequest {
  string hostname = 1;
  string machine_identifier = 2;
  string mac_address = 3;
  google.protobuf.Timestamp last_online = 4;
  DiskInfo disk_info = 5;
  repeated InventoryComponent components = 6;
}

message InventoryComponent {
  string name = 1;
  string technology = 2;
  string type = 3;
  string data_json = 4;
}

message DiskInfo {
  double total_free_gb = 1;
  double os_drive_free_gb = 2;
  map<string, double> drives = 3;
}

message SystemInfoResponse {
  bool success = 1;
  string message = 2;
}
