# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import system_info_pb2 as system__info__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in system_info_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemInfoCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportSystemInfo = channel.unary_unary(
                '/heimdall.telemetry.v1.SystemInfoCollector/ReportSystemInfo',
                request_serializer=system__info__pb2.SystemInfoRequest.SerializeToString,
                response_deserializer=system__info__pb2.SystemInfoResponse.FromString,
                _registered_method=True)
        self.ReportTelemetryBatch = channel.unary_unary(
                '/heimdall.telemetry.v1.SystemInfoCollector/ReportTelemetryBatch',
                request_serializer=system__info__pb2.TelemetryBatchRequest.SerializeToString,
                response_deserializer=system__info__pb2.TelemetryBatchResponse.FromString,
                _registered_method=True)
        self.StreamAgentEvents = channel.stream_unary(
                '/heimdall.telemetry.v1.SystemInfoCollector/StreamAgentEvents',
                request_serializer=system__info__pb2.AgentEventMessage.SerializeToString,
                response_deserializer=system__info__pb2.AgentEventStreamAck.FromString,
                _registered_method=True)
        self.SyncRecipes = channel.unary_unary(
                '/heimdall.telemetry.v1.SystemInfoCollector/SyncRecipes',
                request_serializer=system__info__pb2.RecipeSyncRequest.SerializeToString,
                response_deserializer=system__info__pb2.RecipeSyncResponse.FromString,
                _registered_method=True)


class SystemInfoCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTelemetryBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAgentEvents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncRecipes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemInfoCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSystemInfo,
                    request_deserializer=system__info__pb2.SystemInfoRequest.FromString,
                    response_serializer=system__info__pb2.SystemInfoResponse.SerializeToString,
            ),
            'ReportTelemetryBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTelemetryBatch,
                    request_deserializer=system__info__pb2.TelemetryBatchRequest.FromString,
                    response_serializer=system__info__pb2.TelemetryBatchResponse.SerializeToString,
            ),
            'StreamAgentEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAgentEvents,
                    request_deserializer=system__info__pb2.AgentEventMessage.FromString,
                    response_serializer=system__info__pb2.AgentEventStreamAck.SerializeToString,
            ),
            'SyncRecipes': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncRecipes,
                    request_deserializer=system__info__pb2.RecipeSyncRequest.FromString,
                    response_serializer=system__info__pb2.RecipeSyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heimdall.telemetry.v1.SystemInfoCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heimdall.telemetry.v1.SystemInfoCollector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemInfoCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heimdall.telemetry.v1.SystemInfoCollector/ReportSystemInfo',
            system__info__pb2.SystemInfoRequest.SerializeToString,
            system__info__pb2.SystemInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTelemetryBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heimdall.telemetry.v1.SystemInfoCollector/ReportTelemetryBatch',
            system__info__pb2.TelemetryBatchRequest.SerializeToString,
            system__info__pb2.TelemetryBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAgentEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/heimdall.telemetry.v1.SystemInfoCollector/StreamAgentEvents',
            system__info__pb2.AgentEventMessage.SerializeToString,
            system__info__pb2.AgentEventStreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncRecipes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heimdall.telemetry.v1.SystemInfoCollector/SyncRecipes',
            system__info__pb2.RecipeSyncRequest.SerializeToString,
            system__info__pb2.RecipeSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
